Repository Coteh/simpleimage, pull requests merged in 2021-08, with the labels that each got.

#285 Username auto fill fix
  assets/js/main.js
  views/login-view.ejs
  views/register-view.ejs
Labels: size/S

#290 Add placeholder image that is displayed when direct link is used for image that does not exist
  img/ImageDoesNotExist.png
  img/ImageDoesNotExist.xcf
  lib/routes/route.js
  test/assets/images/BMPtest.bmp
  test/assets/images/GIFtest.gif
  test/assets/images/JPEGtest.jpg
  test/assets/images/PNGtest.png
  test/integ/image_integ_test.js
  test/integ/integ_test_utils.js
  test/integ/user_images_integ_test.js
Labels: size/L

#288 Added Evaluation Mode (#251)
  README.md
  lib/database-ops.js
Labels: size/M

#298 Add image thumbnails to user comments section
  lib/comments.js
  lib/database-ops.js
  lib/routes/route.js
  package-lock.json
  package.json
  test/comments_test.js
  test/integ/change_password_integ_test.js
  test/integ/check_user_login_integ_test.js
  test/integ/integ_test_utils.js
  test/integ/user_comments_integ_test.js
  views/error.ejs
  views/footer.ejs
Labels: size/XL
