Repository Coteh/simpleimage, pull requests merged in 2021-07, with the labels that each got.

#257 Add username check to signup form
  assets/css/form-style.css
  assets/js/main.js
  lib/database-ops.js
  lib/routes/route.js
  lib/util/username.js
  package-lock.json
  package.json
  test/integ/check_username_integ_test.js
  test/util_test.js
  views/register-view.ejs
Labels: size/L

#270 Ensure a session secret is provided in production environment.
  lib/routes/route.js
Labels: size/XS

#271 Replace html encoding function with html-entities library
  lib/util.js
  package-lock.json
  package.json
  test/util_test.js
Labels: size/M

#267 Add Signup to Upload Images mode (#253)
  README.md
  assets/js/file-upload.js
  lib/database-ops.js
  lib/routes/route.js
  test/integ/check_user_login_integ_test.js
  views/index.ejs
Labels: size/M

#280 Fix missing CSRF token with image delete
  assets/js/image.js
  views/image-view.ejs
Labels: size/XS

#282 Allow session secret to have a default value in dev and in test
  lib/routes/route.js
Labels: size/XS
