Repository Coteh/simpleimage, pull requests merged in 2022-04, with the labels that each got.

#367 Update Sentry dependencies to latest
  package-lock.json
  package.json
Labels: size/XS

#372 Refactor routes so they are split into separate files
  .prettierrc
  Makefile
  README.md
  app.js
  assets/js/main.js
  cypress/integration/1-homepage/home.spec.js
  cypress/integration/3-register/register.spec.js
  cypress/integration/5-image/image-page.spec.js
  cypress/integration/6-settings/change-password.spec.js
  cypress/integration/6-settings/settings-home.spec.js
  docker-compose.test.debug.yml
  lib/database-ops.js
  lib/db-util.js
  lib/middleware/csrf.js
  lib/middleware/error.js
  lib/middleware/format.js
  lib/middleware/rate-limit.js
  lib/middleware/session.js
  lib/route/check/index.js
  lib/route/comment/index.js
  lib/route/image/index.js
  lib/route/index.js
  lib/route/login/index.js
  lib/route/logout/index.js
  lib/route/register/index.js
  lib/route/settings/index.js
  lib/route/upload/index.js
  lib/route/user/index.js
  lib/routes/route.js
  lib/server.js
  lib/util/response.js
  package-lock.json
  package.json
  test/integ/change_password_integ_test.js
  test/integ/check_user_login_integ_test.js
  test/integ/check_username_integ_test.js
  test/integ/post_comment_integ_test.js
  test/integ/upload_integ_test.js
  views/index.ejs
  views/settings-view.ejs
Labels: size/XXL

#266 Add more logs for user login, to print the username being logged in
  lib/database-ops.js
Labels: size/XS

#281 Fixes for Delete images prompt is not centered #278
  alvarotorrestx.md
  assets/css/form-style.css
Labels: size/S
